//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by d:\Projects\Petroglyph\ParticleEditor\ParticleEditor.en.rc
//
#define IDS_ERROR_FILE_READ             101
#define IDD_ABOUT                       101
#define IDS_ERROR_FILE_FIND             102
#define IDR_MENU1                       103
#define IDS_ERROR_FILE_WRITE            103
#define IDR_ACCELERATOR1                104
#define IDS_ERROR_FILE_CORRUPT          104
#define IDS_ERROR_FILE_FORMAT           105
#define IDD_RANDOM_PARAMETERS           106
#define IDS_ERROR_XML_PARSER_CREATE     106
#define IDS_ERROR_XML                   107
#define IDD_TRACK_EDITOR                108
#define IDS_ERROR_UI_INITIALIZATION     108
#define IDS_QUERY_DATA_PATH             109
#define IDS_STATUS_MOUSE                110
#define IDS_TOOLTIP_FILE_NEW            111
#define IDS_TOOLTIP_FILE_OPEN           112
#define IDS_TOOLTIP_FILE_SAVE           113
#define IDS_TOOLTIP_TOGGLE_GROUND       114
#define IDS_TOOLTIP_DEBUG_HEAT          115
#define IDD_EMITTER_PROPS1              116
#define IDS_LABEL_BACKGROUND            116
#define IDD_EMITTER_PROPS2              117
#define IDS_LABEL_LEAVE_PARTICLES       117
#define IDD_EMITTER_PROPS3              118
#define IDS_LABEL_TRACK_RED             118
#define IDS_LABEL_TRACK_GREEN           119
#define IDS_LABEL_TRACK_BLUE            120
#define IDS_LABEL_TRACK_ALPHA           121
#define IDS_LABEL_TRACK_SCALE           122
#define IDS_LABEL_TRACK_INDEX           123
#define IDS_LABEL_TRACK_RPS             124
#define IDS_STATUS_SHIFT_TO_SPAWN       125
#define IDS_STATUS_INSTANCES            126
#define IDS_STATUS_PARTICLES            127
#define IDS_STATUS_FPS                  128
#define IDS_QUERY_SAVE_CHANGES          129
#define IDS_WARNING                     130
#define IDS_ERROR_FILE_SAVE             131
#define IDS_FILES_ALO                   132
#define IDS_FILES_ALL                   133
#define IDS_ERROR_FILE_OPEN             134
#define IDS_TITLE_NEW_FILE              135
#define IDD_EMITTER_LIST                136
#define IDS_ERROR_FILE_CREATE           136
#define IDS_ERROR_RENDERER_RESET        137
#define IDS_LABEL_TRACK_NONE            138
#define IDR_NEW_EMITTER_MENU            139
#define IDS_TOOLTIP_KEYS_SELECT         139
#define IDR_EMITTER_CONTEXT_MENU        140
#define IDS_TOOLTIP_KEYS_INSERT         140
#define IDD_RESCALE_SYSTEM              141
#define IDS_TOOLTIP_KEYS_DELETE         141
#define IDD_RESCALE_EMITTER             142
#define IDS_TOOLTIP_INTERPOLATE_LINEAR  142
#define IDS_TOOLTIP_INTERPOLATE_SMOOTH  143
#define IDS_TOOLTIP_INTERPOLATE_STEP    144
#define IDS_PROPPAGE_BASIC              145
#define IDS_PROPPAGE_APPEARANCE         146
#define IDS_PROPPAGE_PHYSICS            147
#define IDS_BLEND_NONE                  148
#define IDS_BLEND_ADDITIVE              149
#define IDS_BLEND_TRANSPARENT           150
#define IDS_BLEND_DEPTH_ADDITIVE        151
#define IDS_BLEND_DEPTH_TRANSPARENT     152
#define IDS_BLEND_DEPTH_INVERSE         153
#define IDS_BLEND_DIFFUSE_TRANSPARENT   154
#define IDS_BLEND_BUMPMAP               155
#define IDS_BLEND_DECAL_BUMPMAP         156
#define IDS_GROUND_BEHAVIOR_NONE        157
#define IDS_GROUND_BEHAVIOR_DISAPPEAR   158
#define IDS_GROUND_BEHAVIOR_BOUNCE      159
#define IDS_GROUND_BEHAVIOR_STICK       160
#define IDS_EMITMODE_DISABLED           161
#define IDS_EMITMODE_RANDOM_VERTEX      162
#define IDS_EMITMODE_RANDOM_MESH        163
#define IDS_EMITMODE_EVERY_VERTEX       164
#define IDS_BLEND_INVERSE               165
#define IDS_TOOLTIP_EMITTER_NEW         166
#define IDS_TOOLTIP_EMITTER_DELETE      167
#define IDS_TOOLTIP_EMITTER_TOGGLE      168
#define IDS_TOOLTIP_EMITTERS_SHOW       169
#define IDS_TOOLTIP_EMITTERS_HIDE       170
#define IDS_PARAMTYPE_EXACT             171
#define IDS_PARAMTYPE_BOX               172
#define IDS_PARAMTYPE_SPHERE            173
#define IDS_PARAMTYPE_CUBE              174
#define IDS_PARAMTYPE_CYLINDER          175
#define IDS_ERROR_EMITTER_COPY          176
#define IDS_ERROR_EMITTER_PASTE         177
#define IDS_EXPAT_COPYRIGHT             178
#define IDS_DISCLAIMER                  179
#define IDC_EDIT1                       1005
#define IDC_EDIT2                       1006
#define IDC_BUTTON1                     1007
#define IDC_BUTTON2                     1008
#define IDC_CHECK1                      1009
#define IDC_CHECK5                      1013
#define IDC_SPINNER1                    1014
#define IDC_SPINNER2                    1015
#define IDC_CHECK7                      1017
#define IDC_SPINNER3                    1018
#define IDC_SPINNER4                    1019
#define IDC_SPINNER5                    1020
#define IDC_SPINNER6                    1021
#define IDC_SPINNER7                    1022
#define IDC_CHECK8                      1023
#define IDC_SPINNER15                   1023
#define IDC_CHECK9                      1024
#define IDC_CHECK10                     1025
#define IDC_CHECK12                     1027
#define IDC_CHECK2                      1029
#define IDC_CHECK14                     1030
#define IDC_CHECK15                     1031
#define IDC_SPINNER8                    1032
#define IDC_SPINNER9                    1033
#define IDC_SPINNER10                   1034
#define IDC_SPINNER11                   1035
#define IDC_SPINNER12                   1036
#define IDC_SPINNER13                   1037
#define IDC_SPINNER16                   1040
#define IDC_SPINNER17                   1041
#define IDC_SPINNER18                   1042
#define IDC_SPINNER19                   1043
#define IDC_SPINNER21                   1045
#define IDC_SPINNER22                   1046
#define IDC_SPINNER23                   1047
#define IDC_SPINNER24                   1048
#define IDC_SPINNER25                   1049
#define IDC_SPINNER26                   1050
#define IDC_SPINNER27                   1051
#define IDC_SPINNER28                   1052
#define IDC_SPINNER31                   1055
#define IDC_SPINNER34                   1058
#define IDC_SPINNER35                   1059
#define IDC_COMBO1                      1060
#define IDC_CHECK16                     1060
#define IDC_STATIC1                     1062
#define IDC_STATIC3                     1063
#define IDC_SPINNER14                   1063
#define IDC_STATIC4                     1064
#define IDC_STATIC5                     1065
#define IDC_STATIC6                     1066
#define IDC_STATIC7                     1067
#define IDC_STATIC8                     1068
#define IDC_STATIC9                     1069
#define IDC_STATIC10                    1070
#define IDC_STATIC11                    1071
#define IDC_STATIC12                    1072
#define IDC_STATIC13                    1073
#define IDC_STATIC2                     1074
#define IDC_EDITOR1                     1077
#define IDC_PARAMS1                     1081
#define IDC_PARAMS2                     1082
#define IDC_TOOLBAR1                    1083
#define IDC_RADIO1                      1084
#define IDC_RADIO2                      1085
#define IDC_COMBO3                      1086
#define IDC_COMBO2                      1087
#define IDC_RADIO3                      1088
#define IDC_EDIT3                       1089
#define IDC_TREE1                       1091
#define IDC_STATIC19                    1092
#define IDC_STATIC27                    1093
#define IDC_STATIC18                    1094
#define IDC_STATIC17                    1095
#define IDC_STATIC25                    1096
#define IDC_STATIC16                    1097
#define IDC_VERSION                     1098
#define IDC_BUILDDATE                   1099
#define IDC_DISCLAIMER                  1100
#define IDC_EXPAT_COPYRIGHT             1101
#define ID_FILE_EXIT                    40001
#define ID_HELP_ABOUT                   40007
#define ID_VIEW_SHOWGROUND              40020
#define ID_VIEW_DEBUGHEAT               40021
#define ID_VIEW_RESETCAMERA             40023
#define ID_NEW_EMITTER_LIFETIME         40033
#define ID_NEW_EMITTER_DEATH            40034
#define ID_NEW_EMITTER_ROOT             40035
#define ID_EDIT_DELETE                  40049
#define ID_EDIT_CLEARALLPARTICLES       40051
#define ID_EMITTER_RENAME               40059
#define ID_PASTEAS_LIFETIME             40068
#define ID_PASTEAS_DEATH                40069
#define ID_EDIT_RESCALE                 40072
#define ID_EMITTER_RESCALE              40076
#define ID_TOGGLE_EMITTER_VISIBILITY    40079
#define ID_SHOW_ALL_EMITTERS            40084
#define ID_HIDE_ALL_EMITTERS            40085

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
